# Generated by Django 5.1.6 on 2025-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='goal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
