# Generated by Django 5.1.6 on 2025-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financialgoal_goal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
