# Generated by Django 5.1.6 on 2025-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financialgoal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('saving', 'Saving'), ('investment', 'Investment'), ('debt_reduction', 'Debt Reduction'), ('retirement', 'Retirement')], max_length=50, null=True),
        ),
    ]
